version: '3'
services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: PG_USER
      POSTGRES_PASSWORD: PG_PASS
      POSTGRES_DB: PG_DATABASE
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - api-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    environment:
      POSTGRES_HOST: postgres 
      POSTGRES_USER: PG_USER
      POSTGRES_PASSWORD: PG_PASS
      POSTGRES_DATABASE: PG_DATABASE
    depends_on:
      - postgres
    networks:
      - api-network

networks:
  api-network:
    driver: bridge

volumes:
  postgres-data:

