name: CI

on:
  push:
    branches: 
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build images
      run: make build

    - name: Run containers
      run: make up

    - name: Test
      run: make test

    - name: Push images
      run: make push