name: learn-github-actions
run-name: ${{ github.aseldar }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker-compose up  --remove-orphans --build
      # - run: go build -o app test_task/app/main.go && HTTP_ADDR=:8080 ./app
      - run: go test -race ./...